const data=[
    {
        id:1,
        title:'Liberated',
        img:'https://puls-img.chanel.com/c_limit,w_768/q_auto:good,f_auto/1637588563801-15973872296291affranchie1930chanelandgigotdjpgmaxmdmdjpeg_1315x974_max_md_md.jpg',
        desc:'We see her again in 1930, wearing trousers and a sailors shirt, with her short hair blowing in the wind. For quite some time, Gabrielle had done nothing like anyone else. For quite some time, she had discovered the happiness of letting her skin darken under the suns caress while spending time in 1920 on Lido’s beaches in Venice in the company of Misia Sert. A life lived in the open air, punctuated by the discovery of sport and leisure, which she indulged in with pleasure: golf, skiing, yachting, fishing, etc. And of course, horseback riding, a passion that began with Étienne Balsan in 1906, which continued with Boy Capel, a distinguished polo player, and the Duke of Westminster. Activities that inspired her to create a wardrobe that was not yet called sportswear, but which laid a foundation that was more current than ever. “I invented the sports dress for myself; not because other women played sports, but because I did. I didn’t go out because I needed to design dresses, I designed dresses precisely because I went out, because I lived, for myself, the life of the century.”* * The Allure of Chanel by Paul Morand, Hermann, 1996. Gabrielle Chanel and her dog Gigot at La Pausa, 1930 © All rights reserved'
    },
    {
        id:2,
        title:'Instinctive',
        img:'https://puls-img.chanel.com/c_limit,w_768/q_auto:good,f_auto/1637589119231-15973872494492instinctive1937photorogerschallphotorogerschallcollectionschalldjpgmaxmdmdjpeg_1029x974_max_md_md.jpg',
        desc:'We see her again in 1910, wearing trousers and a sailors shirt, with her short hair blowing in the wind. For quite some time, Gabrielle had done nothing like anyone else. For quite some time, she had discovered the happiness of letting her skin darken under the suns caress while spending time in 1920 on Lido’s beaches in Venice in the company of Misia Sert. A life lived in the open air, punctuated by the discovery of sport and leisure, which she indulged in with pleasure: golf, skiing, yachting, fishing, etc. And of course, horseback riding, a passion that began with Étienne Balsan in 1906, which continued with Boy Capel, a distinguished polo player, and the Duke of Westminster. Activities that inspired her to create a wardrobe that was not yet called sportswear, but which laid a foundation that was more current than ever. “I invented the sports dress for myself; not because other women played sports, but because I did. I didn’t go out because I needed to design dresses, I designed dresses precisely because I went out, because I lived, for myself, the life of the century.”* * The Allure of Chanel by Paul Morand, Hermann, 1996. Gabrielle Chanel and her dog Gigot at La Pausa, 1910 © All rights reserved'
    },
    {
        id:3,
        title:'Visionary',
        img:'https://puls-img.chanel.com/c_limit,w_768/q_auto:good,f_auto/1637589161136-15973873702153visionnaire1938schallgcdanslolivieralapausadjpgmaxmdmdjpeg_971x974_max_md_md.jpg',
        desc:'We see her again in 1969, wearing trousers and a sailors shirt, with her short hair blowing in the wind. For quite some time, Gabrielle had done nothing like anyone else. For quite some time, she had discovered the happiness of letting her skin darken under the suns caress while spending time in 1920 on Lido’s beaches in Venice in the company of Misia Sert. A life lived in the open air, punctuated by the discovery of sport and leisure, which she indulged in with pleasure: golf, skiing, yachting, fishing, etc. And of course, horseback riding, a passion that began with Étienne Balsan in 1906, which continued with Boy Capel, a distinguished polo player, and the Duke of Westminster. Activities that inspired her to create a wardrobe that was not yet called sportswear, but which laid a foundation that was more current than ever. “I invented the sports dress for myself; not because other women played sports, but because I did. I didn’t go out because I needed to design dresses, I designed dresses precisely because I went out, because I lived, for myself, the life of the century.”* * The Allure of Chanel by Paul Morand, Hermann, 1996. Gabrielle Chanel and her dog Gigot at La Pausa, 1969 © All rights reserved'
    },
    {
        id:4,
        title:'Free',
        img:'https://puls-img.chanel.com/c_limit,w_1920/q_auto:good,f_auto/1637589232383-15973872802364libre1938photoschallinstaircaselapausadjpgmaxmdmdjpeg_1073x974_max_md_md.jpg',
        desc:'“It was the artists who taught me rigor,”* A patron, muse, and sometimes a real pygmalion; a costume designer for theater, ballet and cinema, an avid reader, and passionate about Baroque and Byzantine art and Slavic culture her closest friend, introduced her to this world of constant creativity. Together, their paths crossed with those of Diaghilev, Cocteau, Stravinsky and Dali…We see her again in 1938, wearing trousers and a sailors shirt, with her short hair blowing in the wind. For quite some time, Gabrielle had done nothing like anyone else. For quite some time, she had discovered the happiness of letting her skin darken under the suns caress while spending time in 1920 on Lido’s beaches in Venice in the company of Misia Sert. A life lived in the open air, punctuated by the discovery of sport and leisure, which she indulged in with pleasure: golf, skiing, yachting, fishing, etc. And of course, horseback riding, a passion that began with Étienne Balsan in 1906, which continued with Boy Capel, a distinguished polo player, and the Duke of Westminster. Activities that inspired her to create a wardrobe that was not yet called sportswear, but which laid a foundation that was more current than ever. Gigot at La Pausa, 1938 © All rights reserved'
    },
    {
        id:5,
        title:'Patron',
        img:'https://puls-img.chanel.com/c_limit,w_1920/q_auto:good,f_auto/1637589304213-15973874514745mecene1937chanelandlifar1djpgmaxmdmdjpeg_1389x974_max_md_md.jpg',
        desc:'“Books have been my best friends,”* Gabrielle confided to Paul Morand one day. They never left her, starting with her reading of Psalms at Aubazine Abbey. At Rue Cambon, in her apartments, shelves bend under the weight of books. One of them lays open near a pair of glasses... Lying on her beige suede sofa, on her quilted pillows, Gabrielle reads everything. Sophocles, Homer, Plutarch and Virgil are displayed next to Rabelais, Dante, Shakespeare, and Montaigne. La Bruyère, Molière, Cervantes sit next to Rousseau, Voltaire, and Pascal. We also find Proust, Brontë, Stein, Dostoevsky and Tolstoy. And then there are the poets: Rilke, Baudelaire, Apollinaire, Verlaine, Cocteau, Max Jacob and Reverdy.  * The Allure of Chanel by Paul Morand, Hermann, 1996 Gabrielle Chanel in her apartment - 31 rue Cambon in Paris, 1937 Photo Jean Moral ©  Brigitte Moral'
    },
    {
        id:6,
        title:'Reader',
        img:'https://puls-img.chanel.com/c_limit,w_1920/q_auto:good,f_auto/1637589715988-15973874834206lectrice1937photomoraldjpgmaxmdmdjpeg_1069x974_max_md_md.jpg',
        desc:'Gabrielle helped reveal talent. Naturally, she connected her friends together, inventing the notion of a network well before its time... In 1936, she introduced young Luchino Visconti to director Jean Renoir who, immediately seeing the potential of this young Italian aristocrat who was mad about cinema, hired him as assistant director.“Books have been my best friends,”* Gabrielle confided to Paul Morand one day. They never left her, starting with her reading of Psalms at Aubazine Abbey. At Rue Cambon, in her apartments, shelves bend under the weight of books. One of them lays open near a pair of glasses... Lying on her beige suede sofa, on her quilted pillows, Gabrielle reads everything. Sophocles, Homer, Plutarch and Virgil are displayed next to Rabelais, Dante, Shakespeare, and Montaigne. La Bruyère, Molière, Cervantes sit next to Rousseau, Voltaire, and Pascal. We also find Proust, Brontë, Stein, Dostoevsky and Tolstoy. And then there are the poets: Rilke, Baudelaire, Apollinaire, Verlaine, Cocteau, Max Jacob and Reverdy.  * The Allure of Chanel by Paul Morand, Hermann, 1996 Gabrielle Chanel in her apartment - 31 rue Cambon in Paris, 1937 Photo Jean Moral ©  Brigitte Moral'
    },
    {
        id:7,
        title:'Pygmalion',
        img:'https://puls-img.chanel.com/c_limit,w_1920/q_auto:good,f_auto/1637589869875-15973875033327pygmalion1960sphotogiancarlobottijeannemoreauetgcgettycorbisdjpgmaxmdmdjpeg_628x974_max_md_md.jpg',
        desc:'To learn, to discover, to nurture both her soul and her creativity through the arts: this was a motto that Gabrielle Chanel lived by her entire life.“Books have been my best friends,”* Gabrielle confided to Paul Morand one day. They never left her, starting with her reading of Psalms at Aubazine Abbey. At Rue Cambon, in her apartments, shelves bend under the weight of books. One of them lays open near a pair of glasses... Lying on her beige suede sofa, on her quilted pillows, Gabrielle reads everything. Sophocles, Homer, Plutarch and Virgil are displayed next to Rabelais, Dante, Shakespeare, and Montaigne. La Bruyère, Molière, Cervantes sit next to Rousseau, Voltaire, and Pascal. We also find Proust, Brontë, Stein, Dostoevsky and Tolstoy. And then there are the poets: Rilke, Baudelaire, Apollinaire, Verlaine, Cocteau, Max Jacob and Reverdy.  * The Allure of Chanel by Paul Morand, Hermann, 1996 Gabrielle Chanel in her apartment - 31 rue Cambon in Paris, 1937 Photo Jean Moral ©  Brigitte Moral'
    },
    {
        id:8,
        title:'Art Lover',
        img:'https://puls-img.chanel.com/c_limit,w_1920/q_auto:good,f_auto/1637589969457-15973875244988amoureusedesarts1937photolipnitzki2djpgmaxmdmdjpeg_1034x974_max_md_md.jpg',
        desc:'Breaking down codes, tearing down gender boundaries to launch a classic future for fashion, that of “masculine-feminine,” Gabrielle Chanel dared to do everything.To learn, to discover, to nurture both her soul and her creativity through the arts: this was a motto that Gabrielle Chanel lived by her entire life.“Books have been my best friends,”* Gabrielle confided to Paul Morand one day. They never left her, starting with her reading of Psalms at Aubazine Abbey. At Rue Cambon, in her apartments, shelves bend under the weight of books. One of them lays open near a pair of glasses... Lying on her beige suede sofa, on her quilted pillows, Gabrielle reads everything. Sophocles, Homer, Plutarch and Virgil are displayed next to Rabelais, Dante, Shakespeare, and Montaigne. La Bruyère, Molière, Cervantes sit next to Rousseau, Voltaire, and Pascal. We also find Proust, Brontë, Stein, Dostoevsky and Tolstoy. And then there are the poets: Rilke, Baudelaire, Apollinaire, Verlaine, Cocteau, Max Jacob and Reverdy.  * The Allure of Chanel by Paul Morand, Hermann, 1996 Gabrielle Chanel in her apartment - 31 rue Cambon in Paris, 1937 Photo Jean Moral ©  Brigitte Moral'
    },
    {
        id:9,
        title:'Avant-garde',
        img:'https://puls-img.chanel.com/c_limit,w_1920/q_auto:good,f_auto/1637590084235-15973875456029avantgardiste1938photoschallatlapausadjpgmaxmdmdjpeg_983x974_max_md_md.jpg',
        desc:'When creating N°5, her first perfume, Gabrielle Chanel had to choose between various work samples, and she decided on the fifth sample that was presented to her. Breaking down codes, tearing down gender boundaries to launch a classic future for fashion, that of “masculine-feminine,” Gabrielle Chanel dared to do everything.To learn, to discover, to nurture both her soul and her creativity through the arts: this was a motto that Gabrielle Chanel lived by her entire life.“Books have been my best friends,”* Gabrielle confided to Paul Morand one day. They never left her, starting with her reading of Psalms at Aubazine Abbey. At Rue Cambon, in her apartments, shelves bend under the weight of books. One of them lays open near a pair of glasses... Lying on her beige suede sofa, on her quilted pillows, Gabrielle reads everything. Sophocles, Homer, Plutarch and Virgil are displayed next to Rabelais, Dante, Shakespeare, and Montaigne. La Bruyère, Molière, Cervantes sit next to Rousseau, Voltaire, and Pascal. We also find Proust, Brontë, Stein, Dostoevsky and Tolstoy. And then there are the poets: Rilke, Baudelaire, Apollinaire, Verlaine, Cocteau, Max Jacob and Reverdy.  * The Allure of Chanel by Paul Morand, Hermann, 1996 Gabrielle Chanel in her apartment - 31 rue Cambon in Paris, 1937 Photo Jean Moral ©  Brigitte Moral'
    },
    {
        id:10,
        title:'Luck',
        img:'https://puls-img.chanel.com/c_limit,w_1920/q_auto:good,f_auto/1637590153967-159738789568910chanceimprintofchanelhanddjpgmaxmdmdjpeg_1244x974_max_md_md.jpg',
        desc:' Breaking down codes, tearing down gender boundaries to launch a classic future for fashion, that of “masculine-feminine,” Gabrielle Chanel dared to do everything.To learn, to discover, to nurture both her soul and her creativity through the arts: this was a motto that Gabrielle Chanel lived by her entire life.“Books have been my best friends,”* Gabrielle confided to Paul Morand one day. They never left her, starting with her reading of Psalms at Aubazine Abbey. At Rue Cambon, in her apartments, shelves bend under the weight of books. One of them lays open near a pair of glasses... Lying on her beige suede sofa, on her quilted pillows, Gabrielle reads everything. Sophocles, Homer, Plutarch and Virgil are displayed next to Rabelais, Dante, Shakespeare, and Montaigne. La Bruyère, Molière, Cervantes sit next to Rousseau, Voltaire, and Pascal. We also find Proust, Brontë, Stein, Dostoevsky and Tolstoy. And then there are the poets: Rilke, Baudelaire, Apollinaire, Verlaine, Cocteau, Max Jacob and Reverdy.  * The Allure of Chanel by Paul Morand, Hermann, 1996 Gabrielle Chanel in her apartment - 31 rue Cambon in Paris, 1937 Photo Jean Moral ©  Brigitte Moral'
    }
]
export default data